#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pathlib import Path
import argparse

parser = argparse.ArgumentParser(
  description="Given a [FILE], transpose its content.")
parser.add_argument("file", metavar="FILE", type=str, nargs=1,
  help="A directory of a given [FILE]")
args = parser.parse_args()

class WordMatrix:
  matrix = []

  def __init__(self, text):
    lines = text.split("\n")
    for line in lines:
      words = line.split(" ")
      self.matrix.append(words)

  @staticmethod
  def get_number_of_rows(matrix):
    return len(matrix)

  @staticmethod
  def get_number_of_cols(matrix):
    return len(matrix[0])

  @staticmethod
  def format_output_matrix(matrix):
    rows = self.get_number_Of_rows(matrix)
    cols = self.get_number_Of_cols(matrix)
    for col in range(row):
      "{0}, {1}, {2}".format(matrix[row])
      print("{0}, {1}, {2}".format(matrix[row]))

  def get_transpose(self):
    matrix = self.matrix
    rows = WordMatrix.get_number_of_rows(matrix)
    cols = WordMatrix.get_number_of_cols(matrix)
    transpose_matrix = [[]] * cols
    for col in range(cols):
      matrix[col] = [ None ] * rows
      for row in range(rows):
        transpose_matrix[col][row] = matrix[row][col]
    return matrix


class WordText:
  def __init__(self, file_path):
    path = Path(file_path)
    self.path = path.resolve()

  def get_text(self):
    path = self.path
    if (path.is_file()):
      file = path.open()
      text = file.read()
      file.close()
      return text

class TransposeFile:
  def __init__(self):
    word_text = WordText(file_path=args.file[0])
    word_matrix = WordMatrix(text=word_text.get_text())
    transpose_matrix = word_matrix.get_transpose()
    WordText.format_output_matrix

transposeFile = TransposeFile()
