#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pathlib import Path
import argparse
import sys

class WordMatrix:
  matrix = []

  def __init__(self, text):
    lines = text.split("\n")
    for line in lines:
      if line != "":
        words = line.split(" ")
        self.matrix.append(words)

  @staticmethod
  def get_number_of_rows(matrix):
    return len(matrix)

  @staticmethod
  def get_number_of_cols(matrix):
    return len(matrix[0])

  @staticmethod
  def format_output_matrix(matrix):
    list = []
    rows = WordMatrix.get_number_of_rows(matrix)
    cols = WordMatrix.get_number_of_cols(matrix)
    for row in range(rows):
      list.append(" ".join(matrix[row]))
    return "\n".join(list)

  def get_transpose(self):
    matrix = self.matrix
    rows = WordMatrix.get_number_of_rows(matrix)
    cols = WordMatrix.get_number_of_cols(matrix)
    transpose_matrix = [[]] * cols
    for col in range(cols):
      transpose_matrix[col] = [ None ] * rows
      for row in range(rows):
         transpose_matrix[col][row] = matrix[row][col]
    return transpose_matrix

class TransposeFile:
  def __init__(self, file_path):
    path = Path(file_path)
    self.path = path.resolve()

    word_matrix = WordMatrix(text=self.get_file_content())
    transpose_matrix = word_matrix.get_transpose()
    self.transpose_content = WordMatrix.format_output_matrix(transpose_matrix)

  def get_file_content(self):
    path = self.path
    if (path.is_file()):
      file = path.open()
      text = file.read()
      file.close()
      return text

def main():
  parser = argparse.ArgumentParser(
    description="Given a [FILE], transpose its content.")
  parser.add_argument("file", metavar="FILE", type=str, nargs=1,
    help="A directory of a given [FILE]")
  args = parser.parse_args()

  transpose_file = TransposeFile(file_path=args.file[0])
  text = transpose_file.transpose_content
  sys.stdout.write(text)

main()
