#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from pathlib import Path
import argparse

parser = argparse.ArgumentParser(
  description="Given a [FILE], transpose its content.")
parser.add_argument("file", metavar="FILE", type=str, nargs=1,
  help="A directory of a given [FILE]")
args = parser.parse_args()

class WordMatrix:
  matrix = []

  def __init__(self, text):
    lines = text.split("\n")
    for line in lines:
      words = line.split(" ")
      self.matrix.append(words)

  def get_number_of_rows(self):
    return len(self.matrix)

  def get_number_of_cols(self):
    return len(self.matrix[0])

  def get_transpose(self):
    rows = self.get_number_Of_rows()
    cols = self.get_number_Of_cols()
    transpose_matrix = [[]] * cols
    for col in range(cols):
      matrix[col] = [ None ] * rows
      for row in range(rows):
        transpose_matrix[col][row] = self.matrix[row][col]
    return matrix

class WordText:
  def __init__(self, file_path):
    path = Path(path_string)
    self.path = path.resolve()

  def get_text(self):
    path = self.path
    if (path.is_file()):
      file = path.open()
      text = file.read()
      file.close()
      return text

class TransposeFile:
  def __init__(self):
    wordText = WordText(file_path=args.file[0])
    text = wordText.get_text()
    wordMatrix = WordMatrix(text)

transposeFile = TransposeFile()
